### ISSUE TITLE
sketch task never end

### ISSUE THREAD

**Issue by josedurand** [cognitom/gulp-sketch#27] opened 2016-05-03 16:45 UTC
Hello,

I tested an artboard conversion with a simple sketch file (see image below) and the sketch task start but not never end.

Do you have an Idea ?

thanks for your help
 

Sketch Version : 3.7.2 (28276)

Sketch file:
![capture d ecran 2016-05-03 a 18 08 34](https://cloud.githubusercontent.com/assets/2630691/14989834/17e9d7f6-115a-11e6-87bc-f2d0d02de6a4.png)

gulpfile:
> var gulp   = require('gulp');
> var sketch = require('gulp-sketch');
> var gutil  = require('gulp-util');
> 
> gulp.task('sketch', function(){
>   return gulp.src('*.sketch')
>     .pipe(sketch({
>       export: 'artboards',
>       formats: 'png'
>     })).on('error', gutil.log)
>     .pipe(gulp.dest('./dist/images/'));
> });

**Comment by soenkekluth** [comment] 2016-05-10 21:39
same here - but it actually ends after at least 10 minutes!

**Comment by cognitom** [comment] 2016-05-14 06:56
I couldn't reproduce the issue...
Are you using `gulp-sketch@1.0.0` ?

**Comment by cognitom** [comment] 2016-09-06 02:14
Closing this issue. Feel free to reopen the issue with reproducible example.

**Closed by cognitom** 2016-09-06 02:14 UTC
